### ISSUE TITLE
negative batch duration

### ISSUE THREAD

**Issue by digitalfox** [enioka/jqm#197]
In history table, sometimes the executation date is posterior to end_date. For sure, our batch are not that quick :-).
It could be related to different clock (system, database...) used for execution_date and end_date computation.

**Comment by marcanpilami** [comment]
Good find, and good hypothesis - Loader:316 uses GregorianCalendar.getInstance(Locale.getDefault()) to get the end date, but the Start date is from the database.
The reason behind this is that there are multiple operations to run after the job is done but before we can create the log line... so we simply save the date and create the log later with the saved date. Our goal was to show the 'real' run time of the job instead of 'run time + internal JQM computation'. 

Marking this for next maintenance release - there are other ways to do it.

**Comment by marcanpilami** [comment]
I ended up lowering precision (i.e. taking DB time at the end of the post processing) to keep things simple. The saved time is now only used in case of delayed finalization. After all, the post processing can be considered as part of the payload too.
