### ISSUE TITLE
Classloader leaks with CXF

### ISSUE THREAD

**Issue by jcdugas** [enioka/jqm#200]
Actual JQM implementation is instanciating a classloader for each payload execution, which is fine for payload code hot replacement and isolation, but leads to dangerous classloader leaks with some frameworks (CXF for example). It also increase memory (heap & permgen) consumption of payloads using hibernate for persistence, as each payload instanciates a session factory.

Code isolation between batch modules could be kept by using a classloader for each batch module, and classloader leaks could be avoided by keeping this classloader instanciated for the engine lifetime.

**Comment by marcanpilami** [comment]
Hello,

sorry to hear you had CL leak issues with CXF. The goal of JQM is to be able to run any JSE code, so I will look into it. 

As far as the CL structure is concerned, I do not believe it would be a solution to share classloaders. Indeed, just take the Hibernate example you are giving: JPA2 states that there can only be one persistence.xml file inside the class path. So sharing would mean... only one batch job would be able to connect to the database. This would be rather dire. And keeping one CL per job type would mean needing an incredible amount of memory. That's why I'm classifying this as a bug - which it is. JQM should be able to load without issues any JSE code, irrelevant of its internal structure. (even if the bug is actually something weird done by CXF - it means we need a workaround for this specific type of weirdness).

MA

**Comment by marcanpilami** [comment]
The new CL options should answer this. Also: more recent CXF versions do not have the leak issue.
