### ISSUE TITLE
HibernateClient memory optimisation

### ISSUE THREAD

**Issue by jcdugas** [enioka/jqm#212]
Enqueue() method implementation is creating always the same two Criteria API queries, leading to memory leaks with hibernate query cache. Theses queries should be created at initialisation time and reused each time enqueue method is called.

**Comment by marcanpilami** [comment]
I agree that caching would be very interesting here. What I do not see is why you believe this triggers a memory leak? I've just checked and the query objects are all garbage collectable (once they are use up, there are only soft references pointing to them). So I suppose there is another object I have not seen?

**Comment by jcdugas** [comment]
If you were to use cache for your queries, you would (re)use the same
request object instance, not create a new one.

As for soft references, they are collectable, but only at JVM heap
saturation, that uses a "stop the world" mechanism that should be avoided.

But strictly speaking, you're right, it is not a "real" memory leak...



2016-01-18 17:59 GMT+01:00 marcanpilami <notifications@github.com>:

**Comment by marcanpilami** [comment]
So we agree this would be a welcome modification. I'm setting it for next maintenance release.

Now, for the interesting technical debate... The way I read the doc and blogs (like https://docs.oracle.com/javase/7/docs/api/java/lang/ref/SoftReference.html, http://jeremymanson.blogspot.fr/2009/07/how-hotspot-decides-to-clear_07.html) the normal sweeps (and not only the desperate sweep at the end of memory) can clear soft references. Would you have doc on that?

**Comment by jcdugas** [comment]
Agree with this evolution, that will reduce JQM Client API memory
footprint, postpone full GC execution and reduce its frequency...

Considering the technical debate, my source
<http://neverfear.org/blog/view/150/Strong_Soft_Weak_and_Phantom_References_Java>
is stating
that "Soft references
<http://download.oracle.com/javase/1.4.2/docs/api/java/lang/ref/SoftReference.html>
only
get collected if the JVM absolutely needs the memory."

2016-01-19 14:42 GMT+01:00 marcanpilami <notifications@github.com>:

**Comment by marcanpilami** [comment]
A few final points before closing the issue.

It is sadly not possible to create the queries once and for all (and for example put them in a static variable), because query objects are only valid from within the EntityManager that has created them. The API obviously does not hold an EM open by itself (if only because an EM is not thread safe while the API is) so we cannot cache the queries.

I have therefore chosen an intermediate solution: the use of named queries declared in a parameter file. The doc states that in that case the query should belong to a static context. A few objects should still be created on each call however, but it should be slightly better. A side benefit is that we avoid parsing the query on each call, so the API should be somewhat faster.
