### ISSUE TITLE
Database polling

### ISSUE THREAD

**Issue by schuettec** [enioka/jqm#226]
The manual says that JQM works with database polling. For the polling configuration it is recommended by the manual to not specify a polling frequency shorter that one second.

Please correct me if I'm wrong, because I don't know if I got this right:
Let's say I have a job queue with many jobs and one of the JQM nodes, that was running for a while, has done 2000 jobs successfully. This JQM node has done 2000 jobs, so there were 2000 polls on the database looking for new jobs. Between each of the polls is a wait time not shorter than 1s. That results in a wait time 2000 / 60 > 30 minutes in doing nothing plus the runtime of each job execution. Isn't this a huge amount of time in doing nothing?

**Comment by marcanpilami** [comment]
Hello,

actually, on each poll the node can take multiple jobs (the limit being the max job count you've set for this node/queue association). 

So if the 2000 jobs are inside the queue at the beginning of the test, if each individual job takes <1s to complete, if you have a 100 concurrent jobs limit for this node on this queue, if you poll every second, the node will consume all jobs in 20 seconds.

Does this answer your question (and your worries of course)? If so, I'll file this as a doc bug to clarify it in the next release.

Marc-Antoine

**Comment by schuettec** [comment]
Ah okay, I forgot the worker threads that can handle multiple jobs. Is the field "NBTHREAD" in the section 6.8.2 Defining pollers the "concurrent jobs limit"?

**Comment by marcanpilami** [comment]
Yes, exactly. A poller is simply the association of:
* a queue
* a node (i.e. a JVM)
* a thread count, which defines the max number of jobs the poller can create
* a polling interval, defining how often the poller checks new jobs

Also of note is that... NBTHREAD is not *exactly* a number of thread, since JQM can optionaly (specific job definition option) spawn a new JVM for each job as a workaround for "bad neighbor" jobs. But in the normal use case, it works and renaming the parameter is not really worth it.

**Comment by schuettec** [comment]
Okay thats what I need. Maybe I was misread the docs :-)
Thanks for help!
