### ISSUE TITLE
JQM admin page - error on successful login

### ISSUE THREAD

**Issue by prevereault** [enioka/jqm#240]
Hello,
On some JQM installations, we have the following error page after successful login:
![2016-12-22 jqm 1 4 1-snapshot login error -crop](https://cloud.githubusercontent.com/assets/17875737/21435000/8fd697de-c877-11e6-8c86-908db8c4b47d.png)
(the button "Show advanced error data" does not work)

The root user does not have this problem.

Using JQM 1.4.1-snapshot.
Using web browser Firefox 46.0.1 (corporate configuration).
Clearing cache and restarting Firefox does not solve the issue.
Also Internet Explorer has the same result.

Feel free to ask for more details.
Thanks!
(and Merry XMas & happy holidays!)

**Comment by marcanpilami** [comment]
Hi,

thanks for the report.

could you please open the debug console of Firefox  (F12 key) and retry ? There should be at least one javascript error which will give us more meat for investigations.

MA

**Comment by prevereault** [comment]
Indeed, there is a quite big error log, with a clear summary:
> "NetworkError: 401 Unauthorized - [JQMServer URL here]/common.js"

I feel strange showing the server name and port here, however I can share the full Firebug log and an associated screenshot if needed.

**Comment by marcanpilami** [comment]
Thank you. No need for the server name, you are right to hide environmental data.

This is more than a little weird since all static elements like this javascript file are freely downloadable without authorization. Only the web services are protected. Only thing I can venture from the top of my hat: something weird has happened to the server, like an OutOfMemory error. Could you check the server logs?

**Comment by prevereault** [comment]
I don't think I have access to this server logs, R2-D2, I'll see what I can do tomorrow ;-)
Thank you for your quick responses this late afternoon!

**Comment by marcanpilami** [comment]
I was able to reproduce - I had not understood you were using 1.4.1-SNAPHSOT, and not 1.3.x. It was due to a library upgrade, and is exactly the kind of annoying little things we try to eliminate during this pre-release test period. So thanks a lot for your report. 

To resolve your issue, you can simply download the latest war file [here](https://oss.sonatype.org/service/local/artifact/maven/redirect?r=snapshots&g=com.enioka.jqm&a=jqm-ws&v=1.4.1-SNAPSHOT&e=war) and place it inside JQM_ROOT/webapp (replace the existing file), and restart the JQM server.

**Comment by prevereault** [comment]
Fix confirmed to work on the affected JQM server, thank you!
