### ISSUE TITLE
Crash on long job parameters 

### ISSUE THREAD

**Issue by fabiogermann** [enioka/jqm#288]
When enqueueing a job having a parameter that is longer than 1000 chars the jqm responds with a 500 http error code. 

This is due to the definition of the respective fields in the database as VARCHAR(1000).

Would it be possible to change this to TEXT or similar (without such limitation)?

**Comment by marcanpilami** [comment]
Hi,

parameters exist to emulate the parameters you may give to a program in the command line. You would not set parameters of thousands of characters - you would instead give a file path, or an URL which contains the data you want to process. So (beside the fact that long binary fields such as TEXT are evil for many reasons) this is actually a misuse of the parameters... 

I'll keep the ticket open however because there should be a user exception, not a server exception.
