### ISSUE TITLE
API not exist to operate with Scheduled jobs by name

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#289]
Hi!
I enqueue cron job:
```       JqmClient client = jqmClient();
        JobRequest request = new JobRequest(JobName.PRTDEAL.name(), "root")
                .setPriority(3)
                .setRecurrence("*/5 * * * *")
                .setQueueName(QueueName.NBATCH.getValue())
        int enqueue = client.enqueue(request);
```

In another place, i want to find this schedule by application name and change it, however, this schedule job is not exist in results:
```
        // Here no scheduled job
        List<JobInstance> activeJobs = client.getActiveJobs();
        System.out.println(activeJobs);

        // Here also no scheduled job
        List<JobInstance> jobs = client.getJobs();
        System.out.println(jobs);
```
So, I can't change cron for this schedule, because I don't known ID in this 'other' place.
So, I can't call jqmClient.setScheduleRecurrence(scheduleId, cron);

The goal is to have possibility to change cron, having only application name.
As an solution I want to find this scheduled job by application name, get it schedule Id and call jqmClient.setScheduleRecurrence(scheduleId, cron), but I can't do it.

Can you help me to deal with it? :)

**Comment by marcanpilami** [comment]
So are we talking about a new API which would be getScheduleId(String jobDefAppName) ? But in that case, beware we would return List<Integer> and not a single Integer, as there can be multiple schedules using the same job definition. How would you be sure it is the right one? Or perhaps we could say this API is only for cases when there is only one, and return an exception if there are multiple ones? Or we could add the cron expression as a filter? (but even in this case nothing prevents you from creating multiple schedules with the same expression, even if it is weird).

**Comment by echipachenko** [comment]
I think it can be same as List<JobInstance> getJobs(), but return List of schedules (List<ScheduleJob> getScheduledJobs()) or something like that.
(ScheduleJob - just an schedule object)

And we can iterate over this collections and select schedule what we need, make filtering by name and get schedule id from it.

This variant:
```
List<ScheduleJob> getSchedules(String jobDefAppName)
or
List<ScheduleJob> getSchedules()
```
 is more flexible, because we can see all properties of schedule, we can iterate it, find schedule by property value, etc...

**Comment by echipachenko** [comment]
Hi! Priority information for complemented job is really important feature for us. From QA perspective we want use it for testing and profiling (compare job execution time with specific priority). We have too many tests, which test that specific job submitted with specific priority and executed with it (we make query for completed jobs, find it, and check all properties which we can check with expected result, including priority). 
Another important case: user want to see in job history, how much time was taken by job, and change priority configuration for next run. So, could you include this feature in next snapshot or release build?

**Comment by echipachenko** [comment]
Do you have any updates at this time, please?

**Comment by marcanpilami** [comment]
This was implemented as `JobDef getJobDefinition(String name)` (and the already existing `List\<JobDef> getJobDefinition(String name)` - with the JobDef object gaining a new getSchedule verb.

Note that in this case we have chosen to add a field to the DTO class, because the Schedule object is a weird beast: it can be created through a client call, so seems to be TP data. But it is actually pure metadata, being the template of future Job Instances. So there was no contradiction in adding it to an already existing metadata DTO.

Also note that if you are going through all your schedules at the same time, it is much more efficient to use the verb without parameters `List\<JobDef> getJobDefinition(String name)`  than to call  `JobDef getJobDefinition(String name)` for each name, as it would result in many more database queries.
