### ISSUE TITLE
Changing job priority is not working for running jobs

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#319]
Hi @marcanpilami !

Changing job priority is not working for running jobs.

Thread priority was not changed after changing job priority for the running jobs.

It changes a priority for job instance in DB, but it has no effect in runtime. 
Thread priority hasn't changed.

**Comment by marcanpilami** [comment]
A snapshot has been pushed.

Note that the fix is ugly - it adds a new db query, and like most interactions with running job instances, it only works when the job instance calls an API. A fuller fix, taking place in the engine itself, is supposed to come with #321. As this latter ticket requires some non trivial DB changes it is not to be included in minor versions.
