### ISSUE TITLE
Shared Spring context  'runtimeParameters' not populating with jobs specific values

### ISSUE THREAD

**Issue by simonwibberley** [enioka/jqm#390]
Hi there,

I'm running a Spring Boot application in a shared context provided by JQM as per https://jqm.readthedocs.io/en/jqm-all-2.2.1/jobs/spring.html#by-having-jqm-set-the-context

We're using the API client to submit job requests with different parameters. The parameters seem to be set correctly on the job request / definition and appear as such in the web ui.

![image](https://user-images.githubusercontent.com/299933/76107101-ffa39100-5fcf-11ea-9260-f84f57954011.png)

However the runtime paramters are stuck on those from an arbitrary one from the batch, which are reflected in the logs:

```Job 60287 starting
{
casm.jqm.polling.sitemap=casm.jqm.polling.sitemap false, 
casm.jqm.polling.id=casm.jqm.polling.id www.2.com, 
casm.jqm.polling.threads=casm.jqm.polling.threads 10, 
casm.jqm.crawling.scraper=casm.jqm.crawling.scraper generic, 
casm.jqm.polling.robots=casm.jqm.polling.robots false, 
casm.jqm.polling.depth=casm.jqm.polling.depth 3, 
casm.jqm.polling.filter=casm.jqm.polling.filter .*, 
casm.jqm.polling.agent=casm.jqm.polling.agent http://www.taglaboratory.org/, 
casm.jqm.polling.politeness=casm.jqm.polling.politeness 350, 
casm.jqm.polling.seed=casm.jqm.polling.seed http://www.2.com:5000, 
casm.jqm.sourceDomain=casm.jqm.sourceDomain www.2.com, 
casm.jqm.scraping.scrapers.dir=casm.jqm.scraping.scrapers.dir 
/home/sw206/git/springcrawler/testscrapers, casm.jqm.polling.crawldb=casm.jqm.polling.crawldb 
/home/sw206/git/springcrawler/testcrawldb}

17:24:38.214 [JQMSpringCollector;payload;60287] INFO com.casm.acled.crawler.spring.CrawlerService - Starting config
false
```

Note the 'seed' value is correct on the GUI as `www.99.com`, but incorrect at runtime in the logs `www.2.com`

Any advice greatly appreciated.
Thanks!

**Comment by simonwibberley** [comment]
@marcanpilami could you provide guidance for how to run the appropriate parts of JQM in debug in an IDE so I can investigate further? 

I think I want to break point in `com.enioka.jqm.runner.spring.AnnotationSpringRunner.run()`

Thanks!

**Comment by simonwibberley** [comment]
I'm guessing I need to run `com.enioka.jqm.tools.Main` with `Start-Node -n [node_name] -s conf/resources.xml`

I've set the working dir to `$JQM_ROOT`  but it doesn't seem to find the db config from the XML - it's looking for jqm.properties. 

I provided that with `com.enioka.jqm.jdbc.url=jdbc:postgresql://127.0.0.1:5432/jqm` however `com.enioka.jqm.jdbc.Db` doesn't like postgres:

`java.lang.IllegalArgumentException: this constructor does not support this database type - URL jdbc:postgresql://127.0.0.1:5432/jqm`

Is the startup procedure meant to use jqm.properties or resources.xml for the db config?

Any advice greatly appreciated, thanks!

**Comment by simonwibberley** [comment]
OK, got it `resources.xml` just needed to be in the classpath...

**Comment by simonwibberley** [comment]
So, it turns out the recommended way to get parameters seems unreliable:

```java    
@Resource(name = "runtimeParameters")
private Map<String, String> runtimeParameters;
```
They get stuck on one set.  However, a workaround is to get them from the job manager:
```java
runtimeParameters = jmp.getObject().parameters();
```

**Comment by marcanpilami** [comment]
This is definitely a JQM bug. Thanks for reporting.

**Comment by marcanpilami** [comment]
The bug is that there is an inconsistency between Spring bean scopes: default Spring scope is `singleton`, which means by default beans are only created once. So your job class is only instantiated once. This means that the  `Map<String, String> runtimeParameters` is instantiated with the first values available, and not updated on each run. (that is the reason why we use an ObjectFactory for the job manager and not an instance).

Another workaround is simply to add `@Scope("thread")` to your job class, that way you get a fresh instance on each run. But this is not an actual long term solution, as the `thread` scope is JQM-specific and jobs should not be dependent on JQM.

That "thread dependent" injection of parameters was a hack anyway. The only way to do it properly is through a `@Lookup`. but this cannot be done on a property, only a getter. Or to use an `ObjectFactory`, like for the JobManager. Both options would break ascending compatibility.

Rather than break compatibility in 2.x, I believe we may want to document this (use a special scope if you use runtimeParameters! Also, don't.), deprecate the runtimeParameters bean, and replace it with a factory. (the goal of having a distinct bean than the JobManager was to allow to access parameters without depending on a JQM lib - this would still allow that).

The new sample code would be (no JQM dependencies):
```
    @Resource(name = "runtimeParametersProvider")
    private ObjectFactory<Map<String, String>> parametersProvider;
```

**Comment by marcanpilami** [comment]
Done in 2.2.3 and 3.0
