### ISSUE TITLE
Startup errors

### ISSUE THREAD

**Issue by echipachenko** [enioka/jqm#418]
There is an error on the JQM 2.2.6. immediately after start:
`29/12 13:53:12.368|WARN |JQM engine;;PC-ALF-MAIN                 |Errors           |The following warnings have been detected: HINT: A HTTP GET method, public void com.enioka.jqm.api.ServiceAdmin.getJobDefDeploymentDescriptor(int,javax.servlet.http.HttpServletResponse), returns a void type. It can be intentional and perfectly fine, but it is a little uncommon that GET method returns always "204 No Content".
HINT: A HTTP GET method, public void com.enioka.jqm.api.ServiceAdmin.getJobDefDeploymentDescriptor(javax.servlet.http.HttpServletResponse), returns a void type. It can be intentional and perfectly fine, but it is a little uncommon that GET method returns always "204 No Content".`

**Comment by marcanpilami** [comment]
Hi,

this is a warning (not an error) coming from the JAX-RS library used for the various web service APIs. As it states "It can be intentional and perfectly fine" and in this case it is ;-)
The warning was removed from later versions of the JAX-RS library, but these versions cannot be used in JQM 2.x as they are only not compatible with older Java versions. This library is already updated n the v3.x branch.

So nothing to do here but ignore the warning I'm afraid.
